export const FETCH_RESTAURANT_DETAILS = "FETCH_RESTAURANT_DETAILS";
export const FETCH_TOTAL_ORDERS_AND_COST = "FETCH_TOTAL_ORDERS_AND_COST";
export const FETCH_TOP_FIVE_FOOD = "FETCH_TOP_FIVE_FOOD";
export const FETCH_PROMO_DETAILS = "FETCH_PROMO_DETAILS";
