export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FETCH_FOOD_ITEMS = "FETCH_FOOD_ITEMS";
export const RESET_FOOD_ITEMS = "RESET_FOOD_ITEMS";
// export const ADD_FOOD_ITEM_ORDER = "ADD_FOOD_ITEM_ORDER ";