export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FETCH_FOOD_ITEMS = "FETCH_FOOD_ITEMS";
export const RESET_FOOD_ITEMS = "RESET_FOOD_ITEMS";
export const POST_NEW_ORDER = "POST_NEW_ORDER";
export const RETRIEVE_PROMO_CODES = "RETRIEVE_PROMO_CODES";