export const FETCH_ALL_CUSTOMERS = "FETCH_ALL_CUSTOMERS";
export const FETCH_ALL_ORDERS = "FETCH_ALL_ORDERS";
export const FETCH_ORDERS_BY_MONTH = "FETCH_ORDERS_BY_MONTH";
export const FETCH_ORDERS_BY_CUSTOMER = "FETCH_ORDERS_BY_CUSTOMER";
export const FETCH_ALL_RIDERS_DELIVERIES_INFO =
  "FETCH_ALL_RIDERS_DELIVERIES_INFO";
export const FETCH_RIDER_HOURS = "FETCH_RIDER_HOURS";
