export const FETCH_ORDERS = "FETCH_ORDERS";
export const RESET_ORDERS = "RESET_ORDERS";
export const FETCH_ORDER_DETAILS = "FETCH_ORDER_DETAILS";
export const CREATE_REVIEW = "CREATE_REVIEW";
export const PUT_RIDER_REVIEW = "PUT_RIDER_REVIEW";
